/*
 * dashboard: 仪表数据
 * alarmState: 告警状态
 * machineParamState: 机组参数设定
 * machineState: 机组状态设定
 * switch: 文本状态：text： 数字；alarm：正常/故障； auto: 手动0/自动1; open: 开/关; running: 运行/停止; starting： 启动/停止; control: 主泵1/备用2/检修3/value,
 *         remote: 就地0/远程1; effective： 有效/无效；temp: 恒温0/定值1
 *         可编辑：edit
 * alarm: 告警
 *     alarm: {
 *       des: @String,
 *       expression: @String
 *       level: @Number
 *     };
 * expression:  @String 写入表达式
 * */
const params = {
  metrics: {
    heat_exchanger_temp: {
      name: '温度',
      interval: '30s',
      fields: {
        primary_supply_temp: {
          type: 'float',
          address: '40009',
          desc: '一次分支供温',
          unit: '℃',
          group: 'dashboard',
          position: 'heat_exchanger_temp.fields.primary_supply_temp',
          switch: 'text',
        },
        primary_return_temp: {
          type: 'float',
          address: '40011',
          desc: '一次分支回温',
          unit: '℃',
          group: 'dashboard',
          position: 'heat_exchanger_temp.fields.primary_return_temp',
          switch: 'text',
          alarm: {
            des: '一次回水超温',
            expression: '一次回水温度＞60℃',
            level: 3,
          },
        },
        secondary_supply_temp: {
          type: 'float',
          address: '40013',
          desc: '二次供温',
          unit: '℃',
          group: 'dashboard',
          position: 'heat_exchanger_temp.fields.secondary_supply_temp',
          switch: 'text',
        },
        secondary_return_temp: {
          type: 'float',
          address: '40015',
          desc: '二次回温',
          unit: '℃',
          group: 'dashboard',
          position: 'heat_exchanger_temp.fields.secondary_return_temp',
          switch: 'text',
          alarm: {
            des: '二次回水超温',
            expression: '二次回水温度＞60℃',
            level: 3,
          },
        },
        outdoor_temp: {
          type: 'float',
          address: '40019',
          desc: '室外温度',
          unit: '℃',
          group: 'dashboard',
          position: 'heat_exchanger_temp.fields.outdoor_temp',
          switch: 'text',
        },
        secondary_supply_temp2: {
          type: 'float',
          address: '40065',
          desc: '2#二次供温',
          unit: '℃',
          group: 'dashboard',
          position: 'heat_exchanger_temp.fields.secondary_supply_temp2',
          switch: 'text',
        },
        secondary_supply_temp_setting: {
          type: 'float',
          address: '40111',
          desc: '二次供温实设',
          unit: '℃',
          group: 'machineParamState',
          position: 'heat_exchanger_temp.fields.secondary_supply_temp_setting',
          switch: 'edit',
          expression: '二次供水温度实际设定',
        },
        valve_opening1: {
          type: 'float',
          address: '40117',
          desc: '1#温控阀开度',
          unit: '%',
          group: 'machineParamState',
          position: 'heat_exchanger_temp.fields.valve_opening1',
          switch: 'edit',
          expression: '1#温控阀开度',
        },
      },
    },
    heat_exchanger_pressure: {
      name: '压力',
      interval: '30s',
      fields: {
        primary_supply_pressure: {
          type: 'float',
          address: '40001',
          desc: '一次分支供压',
          unit: 'Mpa',
          group: 'dashboard',
          position: 'heat_exchanger_pressure.fields.primary_supply_pressure',
          switch: 'text',
        },
        primary_return_pressure: {
          type: 'float',
          address: '40003',
          desc: '一次分支回压',
          unit: 'Mpa',
          group: 'dashboard',
          position: 'heat_exchanger_pressure.fields.primary_return_pressure',
          switch: 'text',
        },
        secondary_supply_pressure: {
          type: 'float',
          address: '40005',
          desc: '二次供压',
          unit: 'Mpa',
          group: 'dashboard',
          position: 'heat_exchanger_pressure.fields.secondary_supply_pressure',
          switch: 'text',
        },
        secondary_return_pressure: {
          type: 'float',
          address: '40007',
          desc: '二次回压',
          unit: 'Mpa',
          group: 'dashboard',
          position: 'heat_exchanger_pressure.fields.secondary_return_pressure',
          switch: 'text',
        },
        liquid_level: {
          type: 'float',
          address: '40017',
          desc: '水箱液位',
          unit: '米',
          group: 'dashboard',
          position: 'heat_exchanger_pressure.fields.liquid_level',
          switch: 'text',
        },
        circulating_outlet_pressure: {
          type: 'float',
          address: '40067',
          desc: '循环出口压力',
          unit: 'Mpa',
          group: 'dashboard',
          position: 'heat_exchanger_pressure.fields.circulating_outlet_pressure',
          switch: 'text',
        },
        primary_supply_pressure2: {
          type: 'float',
          address: '40069',
          desc: '一次供压除污后',
          unit: 'Mpa',
          group: 'dashboard',
          position: 'heat_exchanger_pressure.fields.primary_supply_pressure2',
          switch: 'text',
        },
        secondary_return_pressure2: {
          type: 'float',
          address: '40071',
          desc: '二次回压除污后',
          unit: 'Mpa',
          group: 'dashboard',
          position: 'heat_exchanger_pressure.fields.secondary_return_pressure2',
          switch: 'text',
        },
        secondary_return_pressure_setting: {
          type: 'float',
          address: '40081',
          desc: '二次回压设定',
          unit: 'Mpa',
          group: 'machineParamState',
          position: 'heat_exchanger_pressure.fields.secondary_return_pressure_setting',
          switch: 'edit',
          expression: '二次回水压力设定',
        },
        secondary_return_pressure_delta_setting: {
          type: 'float',
          address: '40101',
          desc: '供回压差设定',
          unit: 'Mpa',
          group: 'machineParamState',
          position: 'heat_exchanger_pressure.fields.secondary_return_pressure_delta_setting',
          switch: 'edit',
          expression: '二次供回压差设定',
        },
      },
    },
    heat_exchanger_waterflow: {
      name: '流量数据',
      interval: '60s',
      fields: {
        primary_flow_current: {
          type: 'float',
          address: '40041',
          desc: '一次分支瞬时流量',
          unit: 'm³/h',
          group: 'dashboard',
          position: 'heat_exchanger_waterflow.fields.primary_flow_current',
          switch: 'text',
        },
        secondary_flow_current: {
          type: 'float',
          address: '40053',
          desc: '二次瞬时流量',
          unit: 'm³/h',
          group: 'dashboard',
          position: 'heat_exchanger_waterflow.fields.secondary_flow_current',
          switch: 'text',
        },
        primary_flow_total: {
          type: 'float',
          address: '40043',
          desc: '一次累流',
          unit: 't',
          group: 'dashboard',
          position: 'heat_exchanger_waterflow.fields.primary_flow_total',
          switch: 'text',
        },
        primary_branch_flow_total: {
          type: 'float',
          address: '40045',
          desc: '一次分支累流',
          unit: 't',
          group: 'dashboard',
          position: 'heat_exchanger_waterflow.fields.primary_branch_flow_total',
          switch: 'text',
        },
        secondary_flow_total: {
          type: 'float',
          address: '40055',
          desc: '二次累流',
          unit: 't',
          group: 'dashboard',
          position: 'heat_exchanger_waterflow.fields.secondary_flow_total',
          switch: 'text',
        },
        water_supply: {
          type: 'float',
          address: '40063',
          desc: '补水量',
          unit: 't',
          group: 'dashboard',
          position: 'heat_exchanger_waterflow.fields.water_supply',
          switch: 'text',
        },
        supply_current_flow: {
          type: 'float',
          address: '40061',
          desc: '补水瞬时流量',
          unit: 'm³/h',
          group: 'dashboard',
          position: 'heat_exchanger_waterflow.fields.supply_current_flow',
          switch: 'text',
        },
      },
    },
    heat_exchanger_heating: {
      name: '热量',
      interval: '60s',
      fields: {
        primary_branch_heat_current: {
          type: 'float',
          address: '40047',
          desc: '一次分支瞬时热量',
          unit: 'MJ/h',
          group: 'dashboard',
          position: 'heat_exchanger_heating.fields.primary_branch_heat_current',
          switch: 'text',
        },
        secondary_heat_current: {
          type: 'float',
          address: '40057',
          desc: '二次瞬时热量',
          unit: 'MJ/h',
          group: 'dashboard',
          position: 'heat_exchanger_heating.fields.secondary_heat_current',
          switch: 'text',
        },
        primary_heat_total: {
          type: 'float',
          address: '40049',
          desc: '一次累热',
          unit: 'GJ',
          group: 'dashboard',
          position: 'heat_exchanger_heating.fields.primary_heat_total',
          switch: 'text',
        },
        primary_branch_heat_total: {
          type: 'float',
          address: '40051',
          desc: '一次分支累热',
          unit: 'GJ',
          group: 'dashboard',
          position: 'heat_exchanger_heating.fields.primary_branch_heat_total',
          switch: 'text',
        },
        secondary_heat_total: {
          type: 'float',
          address: '40059',
          desc: '二次累热',
          unit: 'GJ',
          group: 'dashboard',
          position: 'heat_exchanger_heating.fields.secondary_heat_total',
          switch: 'text',
        },
      },
    },
    heat_exchanger_electricity: {
      name: '电表数据',
      interval: '60s',
      fields: {
        electricity_total: {
          type: 'float',
          address: '40157',
          desc: '累计电量',
          unit: 'kW·h',
          group: 'dashboard',
          position: 'heat_exchanger_electricity.fields.electricity_total',
          switch: 'text',
        },
      },
    },
    heat_exchanger_params: {
      name: '换热器参数',
      interval: '60s',
      fields: {
        hydration_status_1: {
          type: 'float',
          address: '40077',
          desc: '1#补水控制',
          unit: '主泵1/备用2/检修3',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.hydration_status_1',
          switch: 'control',
          expression: '1#补水状态',
        },
        hydration_status_2: {
          type: 'float',
          address: '40079',
          desc: '2#补水控制',
          unit: '主泵1/备用2/检修3',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.hydration_status_2',
          switch: 'control',
          expression: '2#补水状态',
        },
        secondary_return_deviation_setting: {
          type: 'float',
          address: '40083',
          desc: '二次回压偏差',
          unit: 'Mpa',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.secondary_return_deviation_setting',
          switch: 'edit',
          expression: '二次回水偏差设定',
        },
        water_refilling_time: {
          type: 'float',
          address: '40085',
          desc: '补水轮换时间',
          unit: '分钟',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.water_refilling_time',
          switch: 'edit',
          expression: '补水轮换时间',
        },
        hydration_frequency_given_1: {
          type: 'float',
          address: '40087',
          desc: '1#补水手动频率',
          unit: 'Hz',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.hydration_frequency_given_1',
          switch: 'edit',
          expression: '1#补水频率给定',
        },
        hydration_frequency_given_2: {
          type: 'float',
          address: '40089',
          desc: '2#补水手动频率',
          unit: 'Hz',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.hydration_frequency_given_2',
          switch: 'edit',
          expression: '2#补水频率给定',
        },
        liquid_level_upper_limit: {
          type: 'float',
          address: '40091',
          desc: '补水阀关液位',
          unit: '米',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.liquid_level_upper_limit',
          switch: 'edit',
          expression: '液位上限',
        },
        liquid_level_lower_limit: {
          type: 'float',
          address: '40093',
          desc: '补水阀开液位',
          unit: '米',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.liquid_level_lower_limit',
          switch: 'edit',
          expression: '液位下限',
        },
        cycle_status_1: {
          type: 'float',
          address: '40095',
          desc: '1#循环控制',
          unit: '主泵1/备用2/检修3',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.cycle_status_1',
          switch: 'control',
          expression: '1#循环状态',
        },
        cycle_status_2: {
          type: 'float',
          address: '40097',
          desc: '2#循环控制',
          unit: '主泵1/备用2/检修3',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.cycle_status_2',
          switch: 'control',
          expression: '2#循环状态',
        },
        cycle_status_3: {
          type: 'float',
          address: '40099',
          desc: '3#循环控制',
          unit: '主泵1/备用2/检修3',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.cycle_status_3',
          switch: 'control',
          expression: '3#循环状态',
        },
        cycle_rotation_time: {
          type: 'float',
          address: '40103',
          desc: '循环轮换时间',
          unit: '分钟',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.cycle_rotation_time',
          switch: 'edit',
          expression: '循环轮换时间',
        },
        cycle_frequency_given_1: {
          type: 'float',
          address: '40105',
          desc: '1#循环手动频率',
          unit: 'Hz',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.cycle_frequency_given_1',
          switch: 'edit',
          expression: '1#循环频率给定',
        },
        cycle_frequency_given_2: {
          type: 'float',
          address: '40107',
          desc: '2#循环手动频率',
          unit: 'Hz',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.cycle_frequency_given_2',
          switch: 'edit',
          expression: '2#循环频率给定',
        },
        cycle_frequency_given_3: {
          type: 'float',
          address: '40109',
          desc: '3#循环手动频率',
          unit: 'Hz',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.cycle_frequency_given_3',
          switch: 'text',
          expression: '3#循环频率给定',
        },
        secondary_supply_temperature_setting: {
          type: 'float',
          address: '40113',
          desc: '二次供温设定',
          unit: '℃',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.secondary_supply_temperature_setting',
          switch: 'edit',
          expression: '二次供水温度设定',
        },
        thermostatic_valve_given_1: {
          type: 'float',
          address: '40115',
          desc: '1#温控阀给定',
          unit: '%',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.thermostatic_valve_given_1',
          switch: 'edit',
          expression: '1#温控阀给定',
        },
        secondary_supply_temperature_setting_2: {
          type: 'float',
          address: '40119',
          desc: '2#二次供温设定',
          unit: '℃',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.secondary_supply_temperature_setting_2',
          switch: 'edit',
          expression: '2#二次供水温度设定',
        },
        thermostatic_valve_given_2: {
          type: 'float',
          address: '40121',
          desc: '2#温控阀给定',
          unit: '%',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.thermostatic_valve_given_2',
          switch: 'edit',
          expression: '2#温控阀给定',
        },
        thermostatic_valve_opening_2: {
          type: 'float',
          address: '40123',
          desc: '2#温控阀开度',
          unit: '%',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.thermostatic_valve_opening_2',
          switch: 'edit',
          expression: '2#温控阀开度',
        },
        liquid_level_low_alarm_setting: {
          type: 'float',
          address: '40125',
          desc: '液位报警',
          unit: '米',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.liquid_level_low_alarm_setting',
          switch: 'edit',
          expression: '液位低报警设定',
        },
        liquid_level_low_protection_setting: {
          type: 'float',
          address: '40127',
          desc: '液位保护',
          unit: '米',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.liquid_level_low_protection_setting',
          switch: 'edit',
          expression: '液位低保护设定',
        },
        back_pressure_low_alarm_setting: {
          type: 'float',
          address: '40129',
          desc: '二次回压报警',
          unit: 'Mpa',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.back_pressure_low_alarm_setting',
          switch: 'edit',
          expression: '回压低报警设定',
        },
        back_pressure_low_protection_setting: {
          type: 'float',
          address: '40131',
          desc: '二次回压保护',
          unit: 'Mpa',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.back_pressure_low_protection_setting',
          switch: 'edit',
          expression: '回压低保护设定',
        },
        secondary_supply_overpressure_setting: {
          type: 'float',
          address: '40133',
          desc: '二次供压超压',
          unit: 'Mpa',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.secondary_supply_overpressure_setting',
          switch: 'edit',
          expression: '二次供水超压设定',
        },
        over_temperature_alarm_setting: {
          type: 'float',
          address: '40135',
          desc: '二次供温超温',
          unit: '℃',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.over_temperature_alarm_setting',
          switch: 'edit',
          expression: '超温报警设定',
        },
        outdoor_control_x1: {
          type: 'float',
          address: '40137',
          desc: '室外控制X1',
          unit: '℃',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.outdoor_control_x1',
          switch: 'edit',
          expression: '室外控制X1',
        },
        outdoor_control_x2: {
          type: 'float',
          address: '40139',
          desc: '室外控制X2',
          unit: '℃',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.outdoor_control_x2',
          switch: 'edit',
          expression: '室外控制X2',
        },
        outdoor_control_x3: {
          type: 'float',
          address: '40141',
          desc: '室外控制X3',
          unit: '℃',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.outdoor_control_x3',
          switch: 'edit',
          expression: '室外控制X3',
        },
        outdoor_control_x4: {
          type: 'float',
          address: '40143',
          desc: '室外控制X4',
          unit: '℃',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.outdoor_control_x4',
          switch: 'edit',
          expression: '室外控制X4',
        },
        outdoor_control_x5: {
          type: 'float',
          address: '40145',
          desc: '室外控制X5',
          unit: '℃',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.outdoor_control_x5',
          switch: 'edit',
          expression: '室外控制X5',
        },
        outdoor_control_y1: {
          type: 'float',
          address: '40147',
          desc: '室外控制Y1',
          unit: '℃',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.outdoor_control_y1',
          switch: 'edit',
          expression: '室外控制Y1',
        },
        outdoor_control_y2: {
          type: 'float',
          address: '40149',
          desc: '室外控制Y2',
          unit: '℃',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.outdoor_control_y2',
          switch: 'edit',
          expression: '室外控制Y2',
        },
        outdoor_control_y3: {
          type: 'float',
          address: '40151',
          desc: '室外控制Y3',
          unit: '℃',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.outdoor_control_y3',
          switch: 'edit',
          expression: '室外控制Y3',
        },
        outdoor_control_y4: {
          type: 'float',
          address: '40153',
          desc: '室外控制Y4',
          unit: '℃',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.outdoor_control_y4',
          switch: 'edit',
          expression: '室外控制Y4',
        },
        outdoor_control_y5: {
          type: 'float',
          address: '40155',
          desc: '室外控制Y5',
          unit: '℃',
          group: 'machineParamState',
          position: 'heat_exchanger_params.fields.outdoor_control_y5',
          switch: 'edit',
          expression: '室外控制Y5',
        },
      },
    },
    heat_exchanger_ctrl: {
      name: '换热器控制',
      interval: '30s',
      fields: {
        hydration_automatic_1: {
          type: 'bit',
          address: '00012',
          desc: '1#补水泵',
          unit: '手动0/自动1',
          group: 'alarmState',
          position: 'heat_exchanger_ctrl.fields.hydration_automatic_1',
          switch: 'auto',
        },
        hydration_automatic_2: {
          type: 'bit',
          address: '00013',
          desc: '2#补水泵',
          unit: '手动0/自动1',
          group: 'alarmState',
          position: 'heat_exchanger_ctrl.fields.hydration_automatic_2',
          switch: 'auto',
        },
        cycle_automatic_1: {
          type: 'bit',
          address: '00014',
          desc: '1#循环泵',
          unit: '手动0/自动1',
          group: 'alarmState',
          position: 'heat_exchanger_ctrl.fields.cycle_automatic_1',
          switch: 'auto',
        },
        cycle_automatic_2: {
          type: 'bit',
          address: '00015',
          desc: '2#循环泵',
          unit: '手动0/自动1',
          group: 'alarmState',
          position: 'heat_exchanger_ctrl.fields.cycle_automatic_2',
          switch: 'auto',
        },
        cycle_automatic_3: {
          type: 'bit',
          address: '00016',
          desc: '3#循环泵',
          unit: '手动0/自动1',
          group: 'alarmState',
          position: 'heat_exchanger_ctrl.fields.cycle_automatic_3',
          switch: 'auto',
        },
        hydration_frequency_conversion_status_1: {
          type: 'bit',
          address: '00017',
          desc: '1#补水变频状态',
          unit: '停止0/运行1',
          group: 'alarmState',
          position: 'heat_exchanger_ctrl.fields.hydration_frequency_conversion_status_1',
          switch: 'running',
        },
        hydration_power_frequency_status_1: {
          type: 'bit',
          address: '00018',
          desc: '1#补水工频状态',
          unit: '停止0/运行1',
          group: 'alarmState',
          position: 'heat_exchanger_ctrl.fields.hydration_power_frequency_status_1',
          switch: 'running',
        },
        hydration_frequency_conversion_status_2: {
          type: 'bit',
          address: '00019',
          desc: '2#补水变频状态',
          unit: '停止0/运行1',
          group: 'alarmState',
          position: 'heat_exchanger_ctrl.fields.hydration_frequency_conversion_status_2',
          switch: 'running',
        },
        hydration_power_frequency_status_2: {
          type: 'bit',
          address: '00020',
          desc: '2#补水工频状态',
          unit: '停止0/运行1',
          group: 'alarmState',
          position: 'heat_exchanger_ctrl.fields.hydration_power_frequency_status_2',
          switch: 'running',
        },
        cycle_frequency_conversion_status_1: {
          type: 'bit',
          address: '00021',
          desc: '1#循环变频状态',
          unit: '停止0/运行1',
          group: 'alarmState',
          position: 'heat_exchanger_ctrl.fields.cycle_frequency_conversion_status_1',
          switch: 'running',
        },
        cycle_power_frequency_status_1: {
          type: 'bit',
          address: '00022',
          desc: '1#循环工频状态',
          unit: '停止0/运行1',
          group: 'alarmState',
          position: 'heat_exchanger_ctrl.fields.cycle_power_frequency_status_1',
          switch: 'running',
        },
        cycle_frequency_conversion_status_2: {
          type: 'bit',
          address: '00023',
          desc: '2#循环变频状态',
          unit: '停止0/运行1',
          group: 'alarmState',
          position: 'heat_exchanger_ctrl.fields.cycle_frequency_conversion_status_2',
          switch: 'running',
        },
        cycle_power_frequency_status_2: {
          type: 'bit',
          address: '00024',
          desc: '2#循环工频状态',
          unit: '停止0/运行1',
          group: 'alarmState',
          position: 'heat_exchanger_ctrl.fields.cycle_power_frequency_status_2',
          switch: 'running',
        },
        cycle_frequency_conversion_status_3: {
          type: 'bit',
          address: '00025',
          desc: '3#循环变频状态',
          unit: '停止0/运行1',
          group: 'alarmState',
          position: 'heat_exchanger_ctrl.fields.cycle_frequency_conversion_status_3',
          switch: 'running',
        },
        cycle_power_frequency_status_3: {
          type: 'bit',
          address: '00026',
          desc: '3#循环工频状态',
          unit: '停止0/运行1',
          group: 'alarmState',
          position: 'heat_exchanger_ctrl.fields.cycle_power_frequency_status_3',
          switch: 'running',
        },
        water_supply_valve_status: {
          type: 'bit',
          address: '00027',
          desc: '补水阀状态',
          unit: '关0/开1',
          group: 'alarmState',
          position: 'heat_exchanger_ctrl.fields.water_supply_valve_status',
          switch: 'open',
        },
        one_fill_two_valve_state: {
          type: 'bit',
          address: '00028',
          desc: '一补二阀状态',
          unit: '关0/开1',
          group: 'alarmState',
          position: 'heat_exchanger_ctrl.fields.one_fill_two_valve_state',
          switch: 'open',
        },
        fault_reset: {
          type: 'bit',
          address: '00029',
          desc: '故障复位',
          unit: '关0/开1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.fault_reset',
          switch: 'open',
          expression: '故障复位',
        },
        automatic_hydration: {
          type: 'bit',
          address: '00030',
          desc: '补水系统',
          unit: '就地0/远程1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.automatic_hydration',
          switch: 'remote',
          expression: '补水自动',
        },
        hydration_frequency_automatic_1: {
          type: 'bit',
          address: '00031',
          desc: '1#补水频率',
          unit: '手动0/自动1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.hydration_frequency_automatic_1',
          switch: 'auto',
          expression: '1#补水频率自动',
        },
        hydration_frequency_automatic_2: {
          type: 'bit',
          address: '00032',
          desc: '2#补水频率',
          unit: '手动0/自动1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.hydration_frequency_automatic_2',
          switch: 'auto',
          expression: '2#补水频率自动',
        },
        hydration_frequency_control_1: {
          type: 'bit',
          address: '00033',
          desc: '1#补水变频',
          unit: '停止0/启动1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.hydration_frequency_control_1',
          switch: 'starting',
          expression: '1#补水变频控制',
        },
        hydration_power_frequency_control_1: {
          type: 'bit',
          address: '00034',
          desc: '1#补水工频',
          unit: '停止0/启动1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.hydration_power_frequency_control_1',
          switch: 'starting',
          expression: '1#补水工频控制',
        },
        hydration_frequency_control_2: {
          type: 'bit',
          address: '00035',
          desc: '2#补水变频',
          unit: '停止0/启动1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.hydration_frequency_control_2',
          switch: 'starting',
          expression: '2#补水变频控制',
        },
        hydration_power_frequency_control_2: {
          type: 'bit',
          address: '00036',
          desc: '2#补水工频',
          unit: '停止0/启动1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.hydration_power_frequency_control_2',
          switch: 'starting',
          expression: '2#补水工频控制',
        },
        fill_valve_automatic: {
          type: 'bit',
          address: '00037',
          desc: '补水阀',
          unit: '手动0/自动1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.fill_valve_automatic',
          switch: 'auto',
          expression: '补水阀自动',
        },
        fill_valve_control: {
          type: 'bit',
          address: '00038',
          desc: '补水阀控制',
          unit: '关闭0/打开1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.fill_valve_control',
          switch: 'open',
          expression: '补水阀控制',
        },
        one_fill_two_valve_automatic: {
          type: 'bit',
          address: '00039',
          desc: '一补二阀',
          unit: '手动0/自动1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.one_fill_two_valve_automatic',
          switch: 'auto',
          expression: '一补二阀自动',
        },
        one_fill_two_valve_control: {
          type: 'bit',
          address: '00040',
          desc: '一补二阀控制',
          unit: '关闭0/打开1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.one_fill_two_valve_control',
          switch: 'open',
          expression: '一补二阀控制',
        },
        automatic_cycle: {
          type: 'bit',
          address: '00041',
          desc: '循环系统',
          unit: '就地0/远程1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.automatic_cycle',
          switch: 'remote',
          expression: '循环自动',
        },
        cycle_frequency_automatic_1: {
          type: 'bit',
          address: '00042',
          unit: '手动0/自动1',
          desc: '1#循环频率',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.cycle_frequency_automatic_1',
          switch: 'auto',
          expression: '1#循环频率自动',
        },
        cycle_frequency_automatic_2: {
          type: 'bit',
          address: '00043',
          unit: '手动0/自动1',
          desc: '2#循环频率',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.cycle_frequency_automatic_2',
          switch: 'auto',
          expression: '2#循环频率自动',
        },
        cycle_frequency_automatic_3: {
          type: 'bit',
          address: '00044',
          unit: '手动0/自动1',
          desc: '3#循环频率',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.cycle_frequency_automatic_3',
          switch: 'auto',
          expression: '3#循环频率自动',
        },
        cycle_frequency_control_1: {
          type: 'bit',
          address: '00045',
          desc: '1#循环变频',
          unit: '停止0/启动1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.cycle_frequency_control_1',
          switch: 'starting',
          expression: '1#循环变频控制',
        },
        cycle_power_frequency_control_1: {
          type: 'bit',
          address: '00046',
          desc: '1#循环工频',
          unit: '停止0/启动1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.cycle_power_frequency_control_1',
          switch: 'starting',
          expression: '1#循环工频控制',
        },
        cycle_frequency_control_2: {
          type: 'bit',
          address: '00047',
          desc: '2#循环变频',
          unit: '停止0/启动1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.cycle_frequency_control_2',
          switch: 'starting',
          expression: '2#循环变频控制',
        },
        cycle_power_frequency_control_2: {
          type: 'bit',
          address: '00048',
          desc: '2#循环工频',
          unit: '停止0/启动1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.cycle_power_frequency_control_2',
          switch: 'starting',
          expression: '2#循环工频控制',
        },
        cycle_frequency_control_3: {
          type: 'bit',
          address: '00049',
          desc: '3#循环变频',
          unit: '停止0/启动1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.cycle_frequency_control_3',
          switch: 'starting',
          expression: '3#循环变频控制',
        },
        cycle_power_frequency_control_3: {
          type: 'bit',
          address: '00050',
          desc: '3#循环工频',
          unit: '停止0/启动1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.cycle_power_frequency_control_3',
          switch: 'starting',
          expression: '3#循环工频控制',
        },
        temperature_compensation_option: {
          type: 'bit',
          address: '00051',
          unit: '无效0/有效1',
          desc: '温度补偿',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.temperature_compensation_option',
          switch: 'effective',
          expression: '温度补偿选择',
        },
        thermostatic_valve_automatic_1: {
          type: 'bit',
          address: '00052',
          desc: '温控方式',
          unit: '恒温0/定值1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.thermostatic_valve_automatic_1',
          switch: 'temp',
          expression: '1#温控阀自动',
        },
        thermostatic_valve_automatic_2: {
          type: 'bit',
          address: '00053',
          desc: '2#温控方式',
          unit: '恒温0/定值1',
          group: 'machineState',
          position: 'heat_exchanger_ctrl.fields.thermostatic_valve_automatic_2',
          switch: 'temp',
          expression: '2#温控阀自动',
        },
      },
    },
    heat_exchanger_waterpump: {
      name: '水泵数据',
      interval: '60s',
      fields: {
        hydration_frequency_1: {
          type: 'float',
          address: '40021',
          desc: '1#补水频率',
          unit: 'Hz',
          group: 'dashboard',
          position: 'heat_exchanger_waterpump.fields.hydration_frequency_1',
          switch: 'text',
        },
        hydration_current_1: {
          type: 'float',
          address: '40023',
          desc: '1#补水电流',
          unit: 'A',
          group: 'dashboard',
          position: 'heat_exchanger_waterpump.fields.hydration_current_1',
          switch: 'text',
        },
        hydration_frequency_2: {
          type: 'float',
          address: '40025',
          desc: '2#补水频率',
          unit: 'Hz',
          group: 'dashboard',
          position: 'heat_exchanger_waterpump.fields.hydration_frequency_2',
          switch: 'text',
        },
        hydration_current_2: {
          type: 'float',
          address: '40027',
          desc: '2#补水电流',
          unit: 'A',
          group: 'dashboard',
          position: 'heat_exchanger_waterpump.fields.hydration_current_2',
          switch: 'text',
        },
        cycle_frequency_1: {
          type: 'float',
          address: '40029',
          desc: '1#循环频率',
          unit: 'Hz',
          group: 'dashboard',
          position: 'heat_exchanger_waterpump.fields.cycle_frequency_1',
          switch: 'text',
        },
        circulating_current_1: {
          type: 'float',
          address: '40031',
          desc: '1#循环电流',
          unit: 'A',
          group: 'dashboard',
          position: 'heat_exchanger_waterpump.fields.circulating_current_1',
          switch: 'text',
        },
        cycle_frequency_2: {
          type: 'float',
          address: '40033',
          desc: '2#循环频率',
          unit: 'Hz',
          group: 'dashboard',
          position: 'heat_exchanger_waterpump.fields.cycle_frequency_2',
          switch: 'text',
        },
        circulating_current_2: {
          type: 'float',
          address: '40035',
          desc: '2#循环电流',
          unit: 'A',
          group: 'dashboard',
          position: 'heat_exchanger_waterpump.fields.circulating_current_2',
          switch: 'text',
        },
        cycle_frequency_3: {
          type: 'float',
          address: '40037',
          desc: '3#循环频率',
          unit: 'Hz',
          group: 'dashboard',
          position: 'heat_exchanger_waterpump.fields.cycle_frequency_3',
          switch: 'text',
        },
        circulating_current_3: {
          type: 'float',
          address: '40039',
          desc: '3#循环电流',
          unit: 'A',
          group: 'dashboard',
          position: 'heat_exchanger_waterpump.fields.circulating_current_3',
          switch: 'text',
        },
        cycle_time: {
          type: 'float',
          address: '40073',
          desc: '循环运行时间',
          unit: '分',
          group: 'dashboard',
          position: 'heat_exchanger_waterpump.fields.cycle_time',
          switch: 'text',
        },
        hydration_running_time: {
          type: 'float',
          address: '40075',
          desc: '补水运行时间',
          unit: '分',
          group: 'dashboard',
          position: 'heat_exchanger_waterpump.fields.hydration_running_time',
          switch: 'text',
        },
      },
    },
    heat_exchanger_alarms: {
      name: '告警状态',
      interval: '30s',
      fields: {
        overpressure_alarm: {
          type: 'bit',
          address: '00001',
          desc: '二次供压超压',
          unit: '正常0/故障1',
          group: 'alarmState',
          position: 'heat_exchanger_alarms.fields.overpressure_alarm',
          switch: 'alarm',
          alarm: {
            des: '二次供压超压',
            expression: '二次供压超压＞0',
            level: 3,
          },
        },
        over_temperature_alarm: {
          type: 'bit',
          address: '00002',
          desc: '二次供温超温',
          unit: '正常0/故障1',
          group: 'alarmState',
          position: 'heat_exchanger_alarms.fields.over_temperature_alarm',
          switch: 'alarm',
          alarm: {
            des: '二次供温超温',
            expression: '二次供温超温＞0',
            level: 3,
          },
        },
        low_return_pressure_alarm: {
          type: 'bit',
          address: '00003',
          desc: '二次回压低压',
          unit: '正常0/故障1',
          group: 'alarmState',
          position: 'heat_exchanger_alarms.fields.low_return_pressure_alarm',
          switch: 'alarm',
          alarm: {
            des: '二次回压低压',
            expression: '二次回压低压＞0',
            level: 3,
          },
        },
        low_liquid_level_alarm: {
          type: 'bit',
          address: '00004',
          desc: '水箱液位低',
          unit: '正常0/故障1',
          group: 'alarmState',
          position: 'heat_exchanger_alarms.fields.low_liquid_level_alarm',
          switch: 'alarm',
          alarm: {
            des: '水箱液位低',
            expression: '水箱液位低＞0',
            level: 3,
          },
        },
        hydration_failure_1: {
          type: 'bit',
          address: '00005',
          desc: '1#补水故障',
          unit: '正常0/故障1',
          group: 'alarmState',
          position: 'heat_exchanger_alarms.fields.hydration_failure_1',
          switch: 'alarm',
          alarm: {
            des: '1#补水故障',
            expression: '1#补水故障＞0',
            level: 3,
          },
        },
        hydration_failure_2: {
          type: 'bit',
          address: '00006',
          desc: '2#补水故障',
          unit: '正常0/故障1',
          group: 'alarmState',
          position: 'heat_exchanger_alarms.fields.hydration_failure_2',
          switch: 'alarm',
          alarm: {
            des: '2#补水故障',
            expression: '2#补水故障＞0',
            level: 3,
          },
        },
        cycle_failure_1: {
          type: 'bit',
          address: '00007',
          desc: '1#循环故障',
          unit: '正常0/故障1',
          group: 'alarmState',
          position: 'heat_exchanger_alarms.fields.cycle_failure_1',
          switch: 'alarm',
          alarm: {
            des: '1#循环故障',
            expression: '1#循环故障＞0',
            level: 3,
          },
        },
        cycle_failure_2: {
          type: 'bit',
          address: '00008',
          desc: '2#循环故障',
          unit: '正常0/故障1',
          group: 'alarmState',
          position: 'heat_exchanger_alarms.fields.cycle_failure_2',
          switch: 'alarm',
          alarm: {
            des: '2#循环故障',
            expression: '2#循环故障＞0',
            level: 3,
          },
        },
        cycle_failure_3: {
          type: 'bit',
          address: '00009',
          desc: '3#循环故障',
          unit: '正常0/故障1',
          group: 'alarmState',
          position: 'heat_exchanger_alarms.fields.cycle_failure_3',
          switch: 'alarm',
          alarm: {
            des: '3#循环故障',
            expression: '3#循环故障＞0',
            level: 3,
          },
        },
        hydration_inverter_failure: {
          type: 'bit',
          address: '00010',
          desc: '补水变频故障',
          unit: '正常0/故障1',
          group: 'alarmState',
          position: 'heat_exchanger_alarms.fields.hydration_inverter_failure',
          switch: 'alarm',
          alarm: {
            des: '补水变频故障',
            expression: '补水变频故障＞0',
            level: 3,
          },
        },
        cycle_inverter_failure: {
          type: 'bit',
          address: '00011',
          desc: '循环变频故障',
          unit: '正常0/故障1',
          group: 'alarmState',
          position: 'heat_exchanger_alarms.fields.cycle_inverter_failure',
          switch: 'alarm',
          alarm: {
            des: '循环变频故障',
            expression: '循环变频故障＞0',
            level: 3,
          },
        },
        comprehensive_alarm: {
          type: 'bit',
          address: '00054',
          desc: '综合报警',
          unit: '系统正常0/系统故障1',
          group: 'alarmState',
          position: 'heat_exchanger_alarms.fields.comprehensive_alarm',
          switch: 'alarm',
          alarm: {
            des: '机组异常',
            expression: '综合报警＞0',
            level: 3,
          },
        },
      },
    },
  },
};

export default params;
